name: projeto_imobiliaria
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  get: ^4.6.5
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  google_maps_flutter: ^2.3.0
  uuid: ^4.1.0
  provider: ^6.1.1
  permission_handler: ^11.0.1
  camera: ^0.10.5+5
  intl: ^0.18.1
  badges: ^3.1.1
  flutter_riverpod: ^2.3.7
  carousel_slider: ^4.2.1
  firebase_database: ^10.4.0
  json_serializable: ^6.6.2
  latlong2: ^0.8.2
  flutter_map: ^4.0.0
  url_launcher: ^6.1.11
  flutter_map_marker_cluster: any
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  file_picker: ^5.3.1
  maplibre_gl: ^0.16.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/images/no_availablle.jpg
  - assets/images/fundo_claro_login.jpg
  - assets/images/favicon.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/favicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/favicon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/favicon.png"