// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXGOmSFDZJbCDZcr7sXCT4nYtAGMCfVQ',
    appId: '1:499780464226:web:3290f0c42a20d0cf03ab3b',
    messagingSenderId: '499780464226',
    projectId: 'imob-projeto-expmed',
    authDomain: 'imob-projeto-expmed.firebaseapp.com',
    storageBucket: 'imob-projeto-expmed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyr_cTj9B6WG2zl6dM_hAr8WzRyDz44I',
    appId: '1:499780464226:android:be50e0f0848274e303ab3b',
    messagingSenderId: '499780464226',
    projectId: 'imob-projeto-expmed',
    storageBucket: 'imob-projeto-expmed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEN5pi1_HYpGxpntwQcLrG0UsAzVimSc',
    appId: '1:499780464226:ios:03ca1d67feb4d83f03ab3b',
    messagingSenderId: '499780464226',
    projectId: 'imob-projeto-expmed',
    storageBucket: 'imob-projeto-expmed.appspot.com',
    iosBundleId: 'com.example.projetoImobiliaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEN5pi1_HYpGxpntwQcLrG0UsAzVimSc',
    appId: '1:499780464226:ios:03ca1d67feb4d83f03ab3b',
    messagingSenderId: '499780464226',
    projectId: 'imob-projeto-expmed',
    storageBucket: 'imob-projeto-expmed.appspot.com',
    iosBundleId: 'com.example.projetoImobiliaria',
  );
}
