class ImovelCaracteristicas {
  late List<String> characteristics;

  ImovelCaracteristicas() {
    characteristics = [
      'banheiros',
      'investidor/ocasião',
      'andar alto',
      'sacada',
      'piscina',
      'sem mobilia',
      'sem elevador',
      'demi suite',
      'lavabos',
      'alto padrão',
      'andar médio',
      'show room',
      'churrasqueira',
      'mobiliado',
      '01 elevador',
      'suite master',
      'VAGAS',
      'MINHA CASA MINHA VIDA',
      'TERRAÇO',
      'SEMI-MOBILIADA',
      '02 OU + ELEVADORES',
      'ACEITA PET',
      'AREA DE LAZER',
      'academia',
      'jardim',
      'varanda gourmet',
      'vista para o mar',
      'portaria 24 horas',
      'sala de cinema',
      'aquecimento a gás',
      'ar condicionado',
      'sistema de segurança',
      'acesso para deficientes',
      'solarium',
      'sistema de irrigação',
      'espaço gourmet',
      'playground',
      'quadra poliesportiva',
      'quadra de tênis',
      'salão de festas',
      'sauna',
      'spa',
      'hidromassagem na piscina',
      'entrada de serviço',
      'entrada social',
      'piso de mármore',
      'portão com controle remoto',
      'prédio frente para o mar',
      'pé direito alto',
      'portas de madeira',
      'móveis planejados',
      'cozinha com armários',
      'área verde',
      'rua asfaltada',
      'vista para o rio',
      'pátio',
      'closet',
      'churrasqueira na sacada',
      'quadra de squash',
      'quadra de futebol de salão',
      'bicicletário',
    ];
  }
}
